name: Build and Publish image to Docker Hub
on:
    pull_request:
        branches:
            - main
jobs:
    publish_image:
        runs-on: ubuntu-latest
        env:
            VERSION: ${{ github.event.pull_request.number }}-${{ github.sha }} # unique version per run
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: build backend image
              run: |
                docker build -f webapp/backend/Dockerfile -t breyr/top-backend:${{ env.VERSION }} .
            - name: build frontend image
              run: |
                docker build -f webapp/frontend/Dockerfile -t breyr/top-frontend:${{ env.VERSION }} .
            - name: build interconnect-api image
              run: |
                docker build -f interconnect-api/Dockerfile -t breyr/top-interconnectapi:${{ env.VERSION }} .
            - name: push images
              run: |
                docker login -u breyr -p ${{ secrets.DOCKER_HUB_TOKEN }}
                docker push breyr/top-backend:${{ env.VERSION }}
                docker push breyr/top-frontend:${{ env.VERSION }}
                docker push breyr/top-interconnectapi:${{ env.VERSION }}