name: Build and Publish image to Docker Hub
on:
    pull_request:
        branches:
            - main
jobs:
    publish_image:
        runs-on: ubuntu-latest
        env:
            VERSION: ${{ github.event.pull_request.number }}-${{ github.sha }} # unique version per run
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: build images
              run: |
                docker build ./webapp/backend/ -t breyr/top-backend:${{ env.VERSION }}
                docker build ./webapp/frontend/ -t breyr/top-frontend:${{ env.VERSION }}
                docker build ./interconnect-api/ -t breyr/top-interconnectapi:${{ env.VERSION }}
            - name: push images
              run: |
                docker login -u breyr -p ${{ secrets.DOCKER_HUB_TOKEN }}
                docker push breyr/top-backend:${{ env.VERSION }}
                docker push breyr/top-frontend:${{ env.VERSION }}
                docker push breyr/top-interconnectapi:${{ env.VERSION }}